import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { getDocPaths } from '@/services/docsService';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        global layout
        {children}
      </body>
    </html>
  );
}

export const dynamicParams = false;

export async function generateStaticParams() {
  const docPaths = await getDocPaths();
  return docPaths.map((item) => ({
    path: item.link.split('/'),
  }));
}
